alias: OMIPS-2018-Pegadito

admin-groups: [OMI-2018]

tags: [omips2018]

generate-output: true
solution: solutions/100B.kj
timeout: 2

validator: validator.py

params:
  title: Pegadito
  source: OMIPS 2018 (Jorge Fernández)

  visibility: 0

  languages: karel

  time_limit: 4000
  memory_limit: 128768
  output_limit: 16384
  stack_limit: 10485760

  overall_wall_time_limit: 60000

  validator: custom
  validator_time_limit: 1000
  extra_wall_time: 0

  email_clarifications: 0
